### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Lancyshah14** [SamSprung/SamSprung-TooIME#28] opened 2022-07-25 13:41 UTC
### Issue Description

The keyboard doesn't show on cover screen

### Logcat Output

```shell
SamSprungIME - #52f3203
Android S (12)
Installed by github

--------- beginning of main
07-25 19:06:48.577  6029  6029 E g.ime:SamSprun: Not starting debugger since process cannot load the jdwp agent.
07-25 19:06:48.581  6029  6029 E USNET   : USNET: appName: com.eightbit.samsprung.ime:SamSprung
07-25 19:06:48.616  6029  6029 D ActivityThread: setConscryptValidator
07-25 19:06:48.617  6029  6029 D ActivityThread: setConscryptValidator - put
--------- beginning of system
07-25 19:06:48.675  6029  6029 D ActivityThread: handleBindApplication()++ app=com.eightbit.samsprung.ime:SamSprung
07-25 19:06:48.676  6029  6029 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 14311; state: ENABLED
07-25 19:06:48.793  6029  6029 D LoadedApk: LoadedApk::makeApplication() appContext.mOpPackageName=com.eightbit.samsprung.ime appContext.mBasePackageName=com.eightbit.samsprung.ime
07-25 19:06:48.793  6029  6029 D NetworkSecurityConfig: No Network Security Config specified, using platform default
07-25 19:06:48.795  6029  6029 D NetworkSecurityConfig: No Network Security Config specified, using platform default
07-25 19:06:48.981  6029  6029 D ActivityThread: handleBindApplication() --
07-25 19:10:49.272  6029 11237 D OpenGLRenderer: RenderThread::requireGlContext()
07-25 19:10:49.273  6029 11237 I AdrenoGLES-0: QUALCOMM build                   : cac6e6f805, I5187d04b75
07-25 19:10:49.273  6029 11237 I AdrenoGLES-0: Build Date                       : 11/22/21
07-25 19:10:49.273  6029 11237 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.35.01.10
07-25 19:10:49.273  6029 11237 I AdrenoGLES-0: Local Branch                     : 
07-25 19:10:49.273  6029 11237 I AdrenoGLES-0: Remote Branch                    : 
07-25 19:10:49.273  6029 11237 I AdrenoGLES-0: Remote Branch                    : 
07-25 19:10:49.273  6029 11237 I AdrenoGLES-0: Reconstruct Branch               : 
07-25 19:10:49.273  6029 11237 I AdrenoGLES-0: Build Config                     : S P 10.0.7 AArch64
07-25 19:10:49.273  6029 11237 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
07-25 19:10:49.287  6029 11237 I AdrenoGLES-0: PFP: 0x016dc094, ME: 0x00000000
07-25 19:10:49.306  6029 11237 D OpenGLRenderer: RenderThread::setGrContext()
07-25 19:10:49.457  6029  6029 I DecorView: [INFO] isPopOver=false, config=true
07-25 19:10:49.457  6029  6029 I DecorView: updateCaptionType >> DecorView@b15a7d5[], isFloating=false, isApplication=true, hasWindowControllerCallback=true, hasWindowDecorCaption=false
07-25 19:10:49.457  6029  6029 D DecorView: setCaptionType = 0, this = DecorView@b15a7d5[]
07-25 19:10:49.460  6029  6029 I DecorView: getCurrentDensityDpi: from real metrics. densityDpi=480 msg=resources_loaded
07-25 19:10:49.545  6029  6029 I WebViewFactory: Loading com.google.android.webview version 103.0.5060.129 (code 506012934)
07-25 19:10:49.562  6029  6029 I cr_WVCFactoryProvider: Loaded version=103.0.5060.129 minSdkVersion=29 isBundle=true multiprocess=true packageId=2
07-25 19:10:49.578  6029  6029 I cr_LibraryLoader: Successfully loaded native library
07-25 19:10:49.579  6029  6029 I cr_CachingUmaRecorder: Flushed 9 samples from 9 histograms.
07-25 19:10:49.589  6029 11254 E SchedPolicy: Failed to find cgroup for tid 6029
07-25 19:10:49.663  6029 11274 E chromium: [ERROR:simple_file_enumerator.cc(21)] opendir /data/user/0/com.eightbit.samsprung.ime/cache/WebView/Default/HTTP Cache/Code Cache/js: No such file or directory (2)
07-25 19:10:49.664  6029 11274 E chromium: [ERROR:simple_index_file.cc(617)] Could not reconstruct index from disk
07-25 19:10:49.666  6029 11258 E chromium: [ERROR:simple_backend_impl.cc(756)] Simple Cache Backend: cache directory inaccessible right after creation; path: /data/user/0/com.eightbit.samsprung.ime/cache/WebView/Default/HTTP Cache/Code Cache/wasm
07-25 19:10:49.668  6029  6029 D CompatibilityChangeReporter: Compat change id reported: 171228096; UID 14311; state: ENABLED
07-25 19:10:49.671  6029 11299 E chromium: [ERROR:disk_cache.cc(204)] Unable to create cache
07-25 19:10:49.674  6029  6029 D ConnectivityManager: StackLog: [android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:4124)] [android.net.ConnectivityManager.registerDefaultNetworkCallbackForUid(ConnectivityManager.java:4688)] [android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:4655)] [Q10.e(chromium-TrichromeWebViewGoogle6432.aab-stable-506012934:142)] [Fb.a(chromium-TrichromeWebViewGoogle6432.aab-stable-506012934:31)] [org.chromium.android_webview.AwContentsLifecycleNotifier.onFirstWebViewCreated(chromium-TrichromeWebViewGoogle6432.aab-stable-506012934:54)] [J.N.MFiR_zHY(Native Method)] [org.chromium.android_webview.AwContents.<init>(chromium-TrichromeWebViewGoogle6432.aab-stable-506012934:49)] [com.android.webview.chromium.o.run(chromium-TrichromeWebViewGoogle6432.aab-stable-506012934:417)] [OE0.b(chromium-TrichromeWebViewGoogle6432.aab-stable-506012934:57)] [NE0.run(chromium-TrichromeWebViewGoogle6432.aab-stable-506012934:43)] [org.chromium.base.task.PostTask.d(chromium-TrichromeWebViewGoogle6432.aab-stable-506012934:115)] [OE0.a(chromium-TrichromeWebViewGoogle6432.aab-stable-506012934:43)] [com.android.webview.chromium.WebViewChromiumFactoryProvider.a(chromium-TrichromeWebViewGoogle6432.aab-stable-506012934:161)] [com.android.webview.chromium.WebViewChromium.init(chromium-TrichromeWebViewGoogle6432.aab-stable-506012934:363)] [android.webkit.WebView.<init>(WebView.java:443)] [android.webkit.WebView.<init>(WebView.java:363)] [android.webkit.WebView.<init>(WebView.java:345)] [android.webkit.WebView.<init>(WebView.java:332)] [java.lang.reflect.Constructor.newInstance0(Native Method)] [java.lang.reflect.Constructor.newInstance(Constructor.java:343)] [android.view.LayoutInflater.createView(LayoutInflater.java:858)] [android.view.LayoutInflater.createView(LayoutInflater.java:780)] [com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)] [android.view.LayoutInflater.onCreateView(LayoutInflater.java:934)] [android.view.LayoutInflater.onCreateView(LayoutInflater.java:954)] [android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1008)] [android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)] [android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)] [android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)] [android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)] [android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)] [android.view.LayoutInflater.inflate(LayoutInflater.java:686)] [android.view.LayoutInflater.inflate(LayoutInflater.java:538)] [android.view.LayoutInflater.inflate(LayoutInflater.java:485)] [androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:11)] [androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:2)] [com.eightbit.samsprung.ime.settings.CoverPreferences.onCreate(CoverPreferences.kt:19)] [android.app.Activity.performCreate(Activity.java:8290)] [android.app.Activity.performCreate(Activity.java:8270)] [android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)] [android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4009)] [android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4201)] [android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)] [android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)] [android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)] [android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)]
07-25 19:10:49.677  6029  6029 D ConnectivityManager: StackLog: [android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:4124)] [android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:4166)] [android.net.ConnectivityManager.registerNetworkCallback(ConnectivityManager.java:4548)] [Q10.e(chromium-TrichromeWebViewGoogle6432.aab-stable-506012934:116)] [Fb.a(chromium-TrichromeWebViewGoogle6432.aab-stable-506012934:31)] [org.chromium.android_webview.AwContentsLifecycleNotifier.onFirstWebViewCreated(chromium-TrichromeWebViewGoogle6432.aab-stable-506012934:54)] [J.N.MFiR_zHY(Native Method)] [org.chromium.android_webview.AwContents.<init>(chromium-TrichromeWebViewGoogle6432.aab-stable-506012934:49)] [com.android.webview.chromium.o.run(chromium-TrichromeWebViewGoogle6432.aab-stable-506012934:417)] [OE0.b(chromium-TrichromeWebViewGoogle6432.aab-stable-506012934:57)] [NE0.run(chromium-TrichromeWebViewGoogle6432.aab-stable-506012934:43)] [org.chromium.base.task.PostTask.d(chromium-TrichromeWebViewGoogle6432.aab-stable-506012934:115)] [OE0.a(chromium-TrichromeWebViewGoogle6432.aab-stable-506012934:43)] [com.android.webview.chromium.WebViewChromiumFactoryProvider.a(chromium-TrichromeWebViewGoogle6432.aab-stable-506012934:161)] [com.android.webview.chromium.WebViewChromium.init(chromium-TrichromeWebViewGoogle6432.aab-stable-506012934:363)] [android.webkit.WebView.<init>(WebView.java:443)] [android.webkit.WebView.<init>(WebView.java:363)] [android.webkit.WebView.<init>(WebView.java:345)] [android.webkit.WebView.<init>(WebView.java:332)] [java.lang.reflect.Constructor.newInstance0(Native Method)] [java.lang.reflect.Constructor.newInstance(Constructor.java:343)] [android.view.LayoutInflater.createView(LayoutInflater.java:858)] [android.view.LayoutInflater.createView(LayoutInflater.java:780)] [com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)] [android.view.LayoutInflater.onCreateView(LayoutInflater.java:934)] [android.view.LayoutInflater.onCreateView(LayoutInflater.java:954)] [android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1008)] [android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)] [android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)] [android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)] [android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)] [android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)] [android.view.LayoutInflater.inflate(LayoutInflater.java:686)] [android.view.LayoutInflater.inflate(LayoutInflater.java:538)] [android.view.LayoutInflater.inflate(LayoutInflater.java:485)] [androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:11)] [androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:2)] [com.eightbit.samsprung.ime.settings.CoverPreferences.onCreate(CoverPreferences.kt:19)] [android.app.Activity.performCreate(Activity.java:8290)] [android.app.Activity.performCreate(Activity.java:8270)] [android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)] [android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4009)] [android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4201)] [android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)] [android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)] [android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)] [android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)]
07-25 19:10:49.699  6029  6029 D RenderScript HIDL Adaptation: IRenderScriptDevice::getService()
07-25 19:10:49.702  6029  6029 D RenderScript HIDL Adaptation: IRenderScriptDevice::getService() returned 0x0
07-25 19:10:49.702  6029  6029 D RenderScript HIDL Adaptation: Using Fallback Path.
07-25 19:10:49.721  6029  6029 D g.ime:SamSprun: Successfully queried cache dir: /data/user_de/0/com.eightbit.samsprung.ime/code_cache
07-25 19:10:49.721  6029  6029 D RenderScript: Setting cache dir: /data/user_de/0/com.eightbit.samsprung.ime/code_cache
07-25 19:10:49.742  6029  6029 W DynamiteModule: Local module descriptor class for com.google.mlkit.dynamite.text.latin not found.
07-25 19:10:49.756  6029 11335 D TransportRuntime.JobInfoScheduler: Scheduling upload for context TransportContext(cct, DEFAULT, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) with jobId=1300703130 in 97974ms(Backend next call timestamp 1658756547729). Attempt 1
07-25 19:10:49.756  6029 11275 W cr_media: Requires BLUETOOTH permission
07-25 19:10:49.785  6029 11237 D NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::BpCustomFrequencyManager()
07-25 19:10:49.787  6029  6029 I DecorView: notifyKeepScreenOnChanged: keepScreenOn=false
07-25 19:10:49.793  6029  6029 I ViewRootImpl@5f518da[CoverPreferences]: setView = com.android.internal.policy.DecorView@b15a7d5 TM=true
07-25 19:10:49.795  6029 11343 I DynamiteModule: Considering local module com.google.android.gms.vision.ocr:0 and remote module com.google.android.gms.vision.ocr:1
07-25 19:10:49.795  6029 11343 I DynamiteModule: Selected remote version of com.google.android.gms.vision.ocr, version >= 1
07-25 19:10:49.814  6029  6029 I WallpaperResourcesInfo: parsingJson: [{"isDefault":true,"isBlackFirstFrame":true,"index":0,"which":2,"screen":0,"type":8,"filename":"B2-Black.mp4","frame_no":300,"cmf_info":["zk"]},{"isDefault":false,"isBlackFirstFrame":true,"index":1,"which":2,"screen":0,"type":8,"filename":"B2-Cream.mp4","frame_no":300,"cmf_info":["ze"]},{"isDefault":false,"isBlackFirstFrame":true,"index":2,"which":2,"screen":0,"type":8,"filename":"B2-Green.mp4","frame_no":300,"cmf_info":["zg"]},{"isDefault":false,"isBlackFirstFrame":true,"index":3,"which":2,"screen":0,"type":8,"filename":"B2-Lavender.mp4","frame_no":300,"cmf_info":["lv"]},{"isDefault":false,"isBlackFirstFrame":true,"index":4,"which":2,"screen":0,"type":8,"filename":"B2-Rose.mp4","frame_no":300,"cmf_info":["li","zb","ia","iw","ig","ib","ba","bw","bi","bg"]},{"isDefault":false,"isBlackFirstFrame":true,"index":5,"which":2,"screen":0,"type":8,"filename":"B2-White.mp4","frame_no":300,"cmf_info":["za","zw","qw","ai","ag","ab","wa","wi","wg","wb"]},{"isDefault":false,"isBlackFirstFrame":true,"index":6,"which":2,"screen":0,"type":8,"filename":"B2-Olive.mp4","frame_no":300,"cmf_info":["lg","ga","gw","gi","qb"]},{"isDefault":true,"isBespoke":true,"index":7,"which":1,"screen":0,"type":0,"filename":"Wallpaper_Bespok_001.png","frame_no":-1,"cmf_info":["1k","1l","1m","1n","1o","4k","4l","4m","4n","4o","1u","1v","1w","1x","1y","4u","4v","4w","4x","4y"]},{"isDefault":false,"isBespoke":true,"index":8,"which":1,"screen":0,"type":0,"filename":"Wallpaper_Bespok_002.png","frame_no":-1,"cmf_info":["1a","1b","1c","1d","1e","4a","4b","4c","4d","4e","1p","1q","1r","1s","1t","4p","4q","4r","4s","4t","1f","1g","1h","1i","1j","4f","4g","4h","4i","4j"]},{"isDefault":true,"isBespoke":true,"index":9,"which":2,"screen":0,"type":0,"filename":"Wallpaper_Bespok_003.png","frame_no":-1,"cmf_info":["1k","1l","1m","1n","1o","4k","4l","4m","4n","4o","1f","1g","1h","1i","1j","4f","4g","4h","4i","4j","1a","1b","1c","1d","1e","4a","4b","4c","4d","4e","1p","1q","1r","1s","1t","4p","4q","4r","4s","4t","1u","1v","1w","1x","1y","4u","4v","4w","4x","4y"]},{"isDefault":false,"index":10,"which":1,"screen":0,"type":0,"filename":"Wallpaper_001.png","frame_no":-1,"cmf_info":["zk"]},{"isDefault":false,"index":11,"which":2,"screen":0,"type":0,"filename":"Wallpaper_002.png","frame_no":-1,"cmf_info":["zk"]},{"isDefault":false,"index":12,"which":1,"screen":0,"type":0,"filename":"Wallpaper_003.png","frame_no":-1,"cmf_info":["ze"]},{"isDefault":false,"index":13,"which":2,"screen":0,"type":0,"filename":"Wallpaper_004.png","frame_no":-1,"cmf_info":["ze"]},{"isDefault":false,"index":14,"which":1,"screen":0,"type":0,"filename":"Wallpaper_005.png","frame_no":-1,"cmf_info":["zg"]},{"isDefault":false,"index":15,"which":2,"screen":0,"type":0,"filename":"Wallpaper_006.png","frame_no":-1,"cmf_info":["zg"]},{"isDefault":false,"index":16,"which":1,"screen":0,"type":0,"filename":"Wallpaper_007.png","frame_no":-1,"cmf_info":["lv"]},{"isDefault":false,"index":17,"which":2,"screen":0,"type":0,"filename":"Wallpaper_008.png","frame_no":-1,"cmf_info":["lv"]},{"isDefault":false,"index":18,"which":1,"screen":0,"type":0,"filename":"Wallpaper_009.png","frame_no":-1,"cmf_info":["li","zb","ia","iw","ig","ib","ba","bw","bi","bg"]},{"isDefault":false,"index":19,"which":2,"screen":0,"type":0,"filename":"Wallpaper_010.png","frame_no":-1,"cmf_info":["li","zb","ia","iw","ig","ib","ba","bw","bi","bg"]},{"isDefault":false,"index":20,"which":1,"screen":0,"type":0,"filename":"Wallpaper_011.png","frame_no":-1,"cmf_info":["za","zw","qw","ai","ag","ab","wa","wi","wg","wb"]},{"isDefault":false,"index":21,"which":2,"screen":0,"type":0,"filename":"Wallpaper_012.png","frame_no":-1,"cmf_info":["za","zw","qw","ai","ag","ab","wa","wi","wg","wb"]},{"isDefault":false,"index":22,"which":1,"screen":0,"type":0,"filename":"Wallpaper_013.png","frame_no":-1,"cmf_info":["lg","ga","gw","gi","qb"]},{"isDefault":false,"index":23,"which":2,"screen":0,"type":0,"filename":"Wallpaper_014.png","frame_no":-1,"cmf_info":["lg","ga","gw","gi","qb"]},{"isDefault":false,"index":24,
07-25 19:10:49.815  6029  6029 D WallpaperManager: peekWallpaperBitmap: which =1, useCache = true
07-25 19:10:49.816  6029  6029 D WallpaperManager: getCurrentWallpaperLocked userId=0 by : com.eightbit.samsprung.ime
07-25 19:10:49.849  6029 11343 W System  : ClassLoader referenced unknown path: 
07-25 19:10:49.850  6029 11335 D TransportRuntime.SQLiteEventStore: Storing event with priority=DEFAULT, name=FIREBASE_ML_SDK for destination cct
07-25 19:10:49.852  6029 11335 D TransportRuntime.JobInfoScheduler: Upload for context TransportContext(cct, DEFAULT, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) is already scheduled. Returning...
07-25 19:10:49.888  6029 11343 W g.ime:SamSprun: ClassLoaderContext classpath size mismatch. expected=8, found=1 (DLC[];PCL[/data/app/~~4VWgS1mOJJ3cqEnSVe-KrQ==/com.google.android.gms-kvP62UNNkCWgddGb_oM5lA==/base.apk*4190054543:/data/app/~~4VWgS1mOJJ3cqEnSVe-KrQ==/com.google.android.gms-kvP62UNNkCWgddGb_oM5lA==/base.apk!classes2.dex*3186385919:/data/app/~~4VWgS1mOJJ3cqEnSVe-KrQ==/com.google.android.gms-kvP62UNNkCWgddGb_oM5lA==/base.apk!classes3.dex*3435741295:/data/app/~~4VWgS1mOJJ3cqEnSVe-KrQ==/com.google.android.gms-kvP62UNNkCWgddGb_oM5lA==/base.apk!classes4.dex*2421759899:/data/app/~~4VWgS1mOJJ3cqEnSVe-KrQ==/com.google.android.gms-kvP62UNNkCWgddGb_oM5lA==/base.apk!classes5.dex*1930124240:/data/app/~~4VWgS1mOJJ3cqEnSVe-KrQ==/com.google.android.gms-kvP62UNNkCWgddGb_oM5lA==/base.apk!classes6.dex*513888653:/data/app/~~4VWgS1mOJJ3cqEnSVe-KrQ==/com.google.android.gms-kvP62UNNkCWgddGb_oM5lA==/base.apk!classes7.dex*3636513543:/data/app/~~4VWgS1mOJJ3cqEnSVe-KrQ==/com.google.android.gms-kvP62UNNkCWgddGb_oM5lA==/base.apk!classes8.dex*2330755871]{PCL[/system/framework/org.apache.http.legacy.jar*128607898]#PCL[/system/framework/com.android.media.remotedisplay.jar*3472798122]#PCL[/system/framework/com.android.location.provider.jar*3633238673]#PCL[/system/system_ext/framework/org.carconnectivity.android.digitalkey.secureelement.jar*3277496666]#PCL[/system_ext/framework/androidx.window.sidecar.jar*181432141]} | DLC[];PCL[/data/app/~~ZX3X0TpEEoEmWH6AZ-Nv_g==/com.eightbit.samsprung.ime-i5klm6APwGPPX4yNSwVlew==/base.apk*2341712085])
07-25 19:10:49.912  6029  6029 D WallpaperManager: checkDeviceDensity getDisplayId=0
07-25 19:10:49.913  6029  6029 D WallpaperManager: checkDeviceDensity deviceRotation=0 deviceHeight=2640 deviceWidth=1080 bitmapHeight=2640 bitmapWidth=1210
07-25 19:10:49.966  6029  6029 I ViewRootImpl@5f518da[CoverPreferences]: Relayout returned: old=(0,0,1080,2640) new=(0,0,1080,2640) req=(1080,2640)0 dur=12 res=0x7 s={true 502299835104} ch=true fn=-1
07-25 19:10:49.972  6029  6029 I ViewRootImpl@5f518da[CoverPreferences]: [DP] dp(1) 1 android.view.ViewRootImpl.reportNextDraw:11387 android.view.ViewRootImpl.performTraversals:4185 android.view.ViewRootImpl.doTraversal:2911 
07-25 19:10:49.975  6029  6029 D ViewRootImpl@5f518da[CoverPreferences]: Creating frameDrawingCallback nextDrawUseBlastSync=false reportNextDraw=true hasBlurUpdates=false
07-25 19:10:49.975  6029  6029 D ViewRootImpl@5f518da[CoverPreferences]: Creating frameCompleteCallback
07-25 19:10:49.976  6029 11237 D OpenGLRenderer: eglCreateWindowSurface
07-25 19:10:50.005  6029 11392 D ViewRootImpl@5f518da[CoverPreferences]: Received frameDrawingCallback frameNum=1. Creating transactionCompleteCallback=false
07-25 19:10:50.013  6029 11237 I BufferQueueProducer: [ViewRootImpl@5f518da[CoverPreferences]#0(BLAST Consumer)0](id:178d00000000,api:1,p:6029,c:6029) queueBuffer: queued for the first time.
07-25 19:10:50.014  6029 11237 D OpenGLRenderer: GPIS:: SetUp Pid : 6029    Tid : 11237
07-25 19:10:50.014  6029 11237 D ViewRootImpl@5f518da[CoverPreferences]: Received frameCompleteCallback  lastAcquiredFrameNum=1 lastAttemptedDrawFrameNum=1
07-25 19:10:50.019  6029  6029 I ViewRootImpl@5f518da[CoverPreferences]: [DP] pdf(0) 1 android.view.ViewRootImpl.lambda$addFrameCompleteCallbackIfNeeded$3$ViewRootImpl:4987 android.view.ViewRootImpl$$ExternalSyntheticLambda16.run:6 android.os.Handler.handleCallback:938 
07-25 19:10:50.019  6029  6029 I ViewRootImpl@5f518da[CoverPreferences]: [DP] rdf()
07-25 19:10:50.019  6029  6029 D ViewRootImpl@5f518da[CoverPreferences]: reportDrawFinished (fn: -1) 
07-25 19:10:50.028  6029  6029 D InsetsSourceConsumer: ensureControlAlpha: for ITYPE_NAVIGATION_BAR on com.eightbit.samsprung.ime/com.eightbit.samsprung.ime.settings.CoverPreferences
07-25 19:10:50.029  6029  6029 D InsetsSourceConsumer: ensureControlAlpha: for ITYPE_STATUS_BAR on com.eightbit.samsprung.ime/com.eightbit.samsprung.ime.settings.CoverPreferences
07-25 19:10:50.029  6029  6029 I ViewRootImpl@5f518da[CoverPreferences]: Relayout returned: old=(0,0,1080,2640) new=(0,0,1080,2640) req=(1080,2640)0 dur=5 res=0x1 s={true 502299835104} ch=false fn=2
07-25 19:10:50.040  6029  6029 I ViewRootImpl@5f518da[CoverPreferences]: MSG_WINDOW_FOCUS_CHANGED 1 1
07-25 19:10:50.042  6029  6029 D InputMethodManager: startInputInner - Id : 0
07-25 19:10:50.042  6029  6029 I InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
07-25 19:10:50.053  6029  6029 D InputMethodManager: startInputInner - Id : 0
07-25 19:10:52.350  6029  6029 I ViewRootImpl@5f518da[CoverPreferences]: ViewPostIme pointer 0
07-25 19:10:52.431  6029  6029 I ViewRootImpl@5f518da[CoverPreferences]: ViewPostIme pointer 1
07-25 19:10:53.033  6029  6029 I ViewRootImpl@5f518da[CoverPreferences]: ViewPostIme pointer 0
07-25 19:10:53.113  6029  6029 I ViewRootImpl@5f518da[CoverPreferences]: ViewPostIme pointer 1
```

### Wiki Confirmation

- [X] I have read the wiki and included a valid log

**Comment by AbandonedCart** [comment] 2022-07-25 14:26
Duplicate of https://github.com/SamSprung/SamSprung-TooIME/issues/25

**Closed by AbandonedCart** 2022-07-25 14:26 UTC
